import { NextRequest, NextResponse } from "next/server";
import { sql } from "@/lib/db";
import { getBuilder } from "@/lib/auth";
import { sendEmail } from "@/lib/mailer";

export const runtime = "nodejs";

// ─── GitHub integration ───────────────────────────────────────────────────────

const GH_TOKEN  = process.env.GITHUB_TOKEN;
const GH_OWNER  = "aluate";
const GH_REPO   = "accwebsite";
const GH_BRANCH = "main";

async function ghGetFileSha(path: string): Promise<string | null> {
  if (!GH_TOKEN) return null;
  try {
    const r = await fetch(
      `https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/contents/${path}?ref=${GH_BRANCH}`,
      { headers: { Authorization: `Bearer ${GH_TOKEN}`, "User-Agent": "acc-website-bot" } }
    );
    if (!r.ok) return null;
    const d = await r.json() as { sha?: string };
    return d.sha ?? null;
  } catch { return null; }
}

async function ghWriteFile(path: string, content: string, message: string, sha?: string | null): Promise<string | null> {
  if (!GH_TOKEN) return null;
  try {
    const body: Record<string, unknown> = {
      message,
      content: Buffer.from(content, "utf8").toString("base64"),
      branch: GH_BRANCH,
    };
    if (sha) body.sha = sha;
    const r = await fetch(
      `https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/contents/${path}`,
      {
        method: "PUT",
        headers: {
          Authorization: `Bearer ${GH_TOKEN}`,
          "Content-Type": "application/json",
          "User-Agent": "acc-website-bot",
        },
        body: JSON.stringify(body),
      }
    );
    if (!r.ok) {
      console.error("[bug-reports] GitHub write failed:", r.status, await r.text());
      return null;
    }
    const d = await r.json() as { content?: { sha?: string } };
    return d.content?.sha ?? null;
  } catch (e) {
    console.error("[bug-reports] GitHub write error:", e);
    return null;
  }
}

function fmtSerial(n: number): string {
  return `BUG-${String(n).padStart(3, "0")}`;
}

function bugMdContent(bug: {
  serial_no: number; severity: string; status: string; triage: string; direction: string | null;
  user_name: string; user_role: string; page_url: string | null;
  what_trying: string; what_happened: string; created_at: string;
}): string {
  const serial  = fmtSerial(bug.serial_no);
  const sevIcon = bug.severity === "blocker" ? "🚨" : bug.severity === "annoying" ? "⚠️" : "ℹ️";
  const date    = new Date(bug.created_at).toLocaleDateString("en-US", { dateStyle: "medium" });

  return [
    `# ${serial}`,
    "",
    `| Field       | Value |`,
    `|-------------|-------|`,
    `| **Serial**  | ${serial} |`,
    `| **Severity**| ${sevIcon} ${bug.severity} |`,
    `| **Status**  | ${bug.status} |`,
    `| **Triage**  | ${bug.triage} |`,
    `| **Reporter**| ${bug.user_name} (${bug.user_role}) |`,
    `| **Page**    | ${bug.page_url ?? "—"} |`,
    `| **Date**    | ${date} |`,
    "",
    "## What they were trying to do",
    "",
    bug.what_trying,
    "",
    "## What happened instead",
    "",
    bug.what_happened,
    "",
    "## Direction / Context",
    "",
    bug.direction?.trim() || "*(no direction set — add context in admin bug triage)*",
    "",
  ].join("\n");
}

async function rebuildLogMd(): Promise<void> {
  if (!GH_TOKEN) return;
  try {
    const rows = await sql<{
      serial_no: number; severity: string; status: string; triage: string;
      what_trying: string; created_at: string;
    }>`
      SELECT serial_no, severity, status, triage, what_trying, created_at
      FROM bug_reports
      WHERE serial_no IS NOT NULL
      ORDER BY serial_no ASC
    `;

    const sevIcon = (s: string) => s === "blocker" ? "🚨" : s === "annoying" ? "⚠️" : "ℹ️";
    const tableRows = rows.map((r) => {
      const serial  = fmtSerial(r.serial_no);
      const date    = new Date(r.created_at).toLocaleDateString("en-US", { dateStyle: "short" });
      const summary = r.what_trying.replace(/[|]/g, "\\|").slice(0, 60) + (r.what_trying.length > 60 ? "…" : "");
      return `| [${serial}](bugs/${serial}.md) | ${sevIcon(r.severity)} ${r.severity} | ${r.status} | ${r.triage} | ${summary} | ${date} |`;
    });

    const open     = rows.filter((r) => r.status === "open" && r.triage !== "skip").length;
    const fixCount = rows.filter((r) => r.triage === "fix" && r.status !== "fixed").length;

    const content = [
      "# ACC Bug Log",
      "",
      `> Auto-generated by acc-website. Last updated: ${new Date().toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}`,
      "",
      `**Open: ${open}  |  Fix queue: ${fixCount}  |  Total: ${rows.length}**`,
      "",
      "## Triage Guide",
      "",
      "- **open** — not yet triaged",
      "- **fix** — Claude should fix this in the next session",
      "- **skip** — won't fix / not a bug",
      "- **context** — added direction, needs more info or scheduled later",
      "",
      "## Bug Index",
      "",
      "| # | Severity | Status | Triage | Summary | Date |",
      "|---|----------|--------|--------|---------|------|",
      ...tableRows,
      "",
    ].join("\n");

    const sha = await ghGetFileSha("bugs/LOG.md");
    await ghWriteFile("bugs/LOG.md", content, "chore: update bug LOG.md", sha);
  } catch (e) {
    console.error("[bug-reports] rebuildLogMd error:", e);
  }
}

// ─── Route handlers ───────────────────────────────────────────────────────────

async function ensureTable() {
  await sql`
    CREATE TABLE IF NOT EXISTS bug_reports (
      id            TEXT        PRIMARY KEY DEFAULT gen_random_uuid()::text,
      serial_no     INTEGER,
      page_url      TEXT,
      user_name     TEXT,
      user_role     TEXT,
      what_trying   TEXT        NOT NULL,
      what_happened TEXT        NOT NULL,
      severity      TEXT        NOT NULL DEFAULT 'annoying',
      status        TEXT        NOT NULL DEFAULT 'open',
      triage        TEXT        NOT NULL DEFAULT 'open',
      direction     TEXT,
      gh_file_sha   TEXT,
      created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  // Idempotent column adds for existing tables
  for (const stmt of [
    `ALTER TABLE bug_reports ADD COLUMN IF NOT EXISTS serial_no   INTEGER`,
    `ALTER TABLE bug_reports ADD COLUMN IF NOT EXISTS triage      TEXT NOT NULL DEFAULT 'open'`,
    `ALTER TABLE bug_reports ADD COLUMN IF NOT EXISTS direction   TEXT`,
    `ALTER TABLE bug_reports ADD COLUMN IF NOT EXISTS gh_file_sha TEXT`,
  ]) {
    await sql.unsafe(stmt).catch(() => {/* already exists */});
  }
}

function uid() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
}

export async function POST(req: NextRequest) {
  await ensureTable();

  const session = await getBuilder().catch(() => null);
  const body = await req.json() as {
    page_url?: string;
    what_trying?: string;
    what_happened?: string;
    severity?: string;
  };

  const { page_url, what_trying, what_happened, severity } = body;
  if (!what_trying?.trim() || !what_happened?.trim()) {
    return NextResponse.json({ error: "Both fields are required" }, { status: 400 });
  }

  const validSeverity = ["blocker", "annoying", "minor"].includes(severity ?? "")
    ? severity! : "annoying";

  const id  = uid();
  const now = new Date().toISOString();
  const user_name = session?.name ?? "Unknown";
  const user_role = session?.role ?? "unknown";

  // Get next serial number
  const [{ max_serial }] = await sql<{ max_serial: number | null }>`
    SELECT MAX(serial_no) AS max_serial FROM bug_reports
  `;
  const serial_no = (max_serial ?? 0) + 1;
  const serial    = fmtSerial(serial_no);

  await sql`
    INSERT INTO bug_reports (id, serial_no, user_name, user_role, page_url, what_trying, what_happened, severity, status, triage, created_at)
    VALUES (
      ${id}, ${serial_no}, ${user_name}, ${user_role},
      ${page_url ?? null},
      ${what_trying.trim()},
      ${what_happened.trim()},
      ${validSeverity},
      'open', 'open',
      ${now}
    )
  `;

  // Write to GitHub (non-blocking — don't fail the request if GitHub is unavailable)
  const bugRecord = {
    serial_no, severity: validSeverity, status: "open", triage: "open", direction: null,
    user_name, user_role, page_url: page_url ?? null,
    what_trying: what_trying.trim(), what_happened: what_happened.trim(), created_at: now,
  };
  const filePath = `bugs/${serial}.md`;
  const sha = await ghWriteFile(filePath, bugMdContent(bugRecord), `bug: add ${serial} from ${user_name}`);
  if (sha) {
    await sql`UPDATE bug_reports SET gh_file_sha = ${sha} WHERE id = ${id}`.catch(() => {});
    await rebuildLogMd();
  }

  const sevIcon  = validSeverity === "blocker" ? "🚨" : validSeverity === "annoying" ? "⚠️" : "ℹ️";
  const sevLabel = validSeverity.toUpperCase();

  try {
    await sendEmail({
      to: "karlv@advancedcabinets.net",
      subject: `${sevIcon} [${serial}] [${sevLabel}] Bug from ${user_name} — ${page_url ?? "unknown page"}`,
      text: [
        `Serial: ${serial}`,
        `Reporter: ${user_name} (${user_role})`,
        `Page: ${page_url ?? "unknown"}`,
        `Severity: ${sevLabel}`,
        ``,
        `What they were trying to do:`,
        what_trying.trim(),
        ``,
        `What happened instead:`,
        what_happened.trim(),
        ``,
        `Submitted: ${new Date(now).toLocaleString("en-US", { timeZone: "America/Los_Angeles" })}`,
        ``,
        `Triage in admin: https://advancedcabinets.org/admin/bugs`,
        GH_TOKEN ? `GitHub: https://github.com/${GH_OWNER}/${GH_REPO}/blob/main/bugs/${serial}.md` : "",
      ].filter(Boolean).join("\n"),
    });
  } catch {
    // Email failure doesn't fail the request
  }

  return NextResponse.json({ ok: true, id, serial });
}

export async function GET(req: NextRequest) {
  const session = await getBuilder().catch(() => null);
  if (!session || (session.role !== "admin" && session.role !== "karl")) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
  }

  await ensureTable();
  const { searchParams } = new URL(req.url);
  const status = searchParams.get("status") ?? "open";

  const rows = status === "all"
    ? await sql`
        SELECT * FROM bug_reports
        ORDER BY
          CASE status WHEN 'open' THEN 0 ELSE 1 END,
          CASE severity WHEN 'blocker' THEN 1 WHEN 'annoying' THEN 2 ELSE 3 END,
          created_at ASC
      `
    : await sql`
        SELECT * FROM bug_reports
        WHERE status = ${status}
        ORDER BY
          CASE severity WHEN 'blocker' THEN 1 WHEN 'annoying' THEN 2 ELSE 3 END,
          created_at ASC
      `;

  return NextResponse.json({ bugs: rows });
}

export async function PATCH(req: NextRequest) {
  const session = await getBuilder().catch(() => null);
  if (!session || (session.role !== "admin" && session.role !== "karl")) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
  }

  const body = await req.json() as {
    id: string;
    status?: string;
    triage?: string;
    direction?: string;
  };
  if (!body.id) return NextResponse.json({ error: "id required" }, { status: 400 });

  const updates: string[] = [];
  if (body.status)    updates.push("status");
  if (body.triage !== undefined) updates.push("triage");
  if (body.direction !== undefined) updates.push("direction");

  if (updates.length === 0) return NextResponse.json({ ok: true });

  // Fetch current row for GitHub update
  const [row] = await sql<{
    serial_no: number | null; severity: string; status: string; triage: string;
    direction: string | null; user_name: string; user_role: string;
    page_url: string | null; what_trying: string; what_happened: string;
    created_at: string; gh_file_sha: string | null;
  }>`SELECT * FROM bug_reports WHERE id = ${body.id}`;

  if (!row) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const newStatus    = body.status    ?? row.status;
  const newTriage    = body.triage    ?? row.triage;
  const newDirection = body.direction ?? row.direction;

  await sql`
    UPDATE bug_reports
    SET status    = ${newStatus},
        triage    = ${newTriage},
        direction = ${newDirection ?? null}
    WHERE id = ${body.id}
  `;

  // Update GitHub file if we have a serial
  if (row.serial_no) {
    const updatedRecord = {
      ...row,
      status: newStatus,
      triage: newTriage,
      direction: newDirection ?? null,
    };
    const filePath = `bugs/${fmtSerial(row.serial_no)}.md`;
    const sha = row.gh_file_sha ?? await ghGetFileSha(filePath);
    const newSha = await ghWriteFile(
      filePath,
      bugMdContent(updatedRecord),
      `bug: update ${fmtSerial(row.serial_no)} triage=${newTriage}`,
      sha
    );
    if (newSha) {
      await sql`UPDATE bug_reports SET gh_file_sha = ${newSha} WHERE id = ${body.id}`.catch(() => {});
      await rebuildLogMd();
    }
  }

  return NextResponse.json({ ok: true });
}
