/**
 * scripts/seed-jobs.ts
 * One-time import of residential job stubs from Z-drive folder scan.
 * Run: npx tsx scripts/seed-jobs.ts
 */
import { sql, nextJobId } from "../lib/db";

const jobs = [
  {
    status: `pre-engineering`,
    client_name: `Almighty Construction`,
    site_address: `2112 W Mitchell Bay Rd`,
    builder_company: `Almighty Construction`,
    notes: `Estimating folder: Almighty Construction - 2112 W Mitchell Bay Rd | Latest quote: 2026-03-04`,
  },
  {
    status: `pre-engineering`,
    client_name: `Bar 17`,
    site_address: `1007 Grove Way Townhouses`,
    builder_company: `Bar 17`,
    notes: `Estimating folder: Bar 17 - 1007 Grove Way Townhouses | No quote on file — plans only`,
  },
  {
    status: `pre-engineering`,
    client_name: `Benson`,
    site_address: `TBD`,
    builder_company: `Benson`,
    notes: `Estimating folder: Benson Residence | Multiple finish options quoted (Rift Cut White Oak + Alder) | Latest quote: 2026-02-23`,
  },
  {
    status: `pre-engineering`,
    client_name: `Cobalt Construction`,
    site_address: `2761 Lumber Lane`,
    builder_company: `Cobalt Construction`,
    notes: `Estimating folder: Cobalt Construction - 2761 Lumber Lane C Plan | Drawings only (4/28) — no quote file found`,
  },
  {
    status: `pre-engineering`,
    client_name: `Cobalt Construction`,
    site_address: `2775 Lumber Lane`,
    builder_company: `Cobalt Construction`,
    notes: `Estimating folder: Cobalt Construction - 2775 Lumber Lane A Plan | No quote or drawings found`,
  },
  {
    status: `pre-engineering`,
    client_name: `Premier`,
    site_address: `TBD`,
    builder_company: `Premier`,
    notes: `Estimating folder: Crooks - Premier | Latest quote: 2026-04-30`,
  },
  {
    status: `pre-engineering`,
    client_name: `Helena`,
    site_address: `TBD`,
    builder_company: `Helena`,
    notes: `Estimating folder: Helena Wardrobe | Wardrobe only — not a full kitchen | Latest quote: 2026-03-10`,
  },
  {
    status: `pre-engineering`,
    client_name: `John Fortuny`,
    site_address: `TBD`,
    builder_company: `John Fortuny`,
    notes: `Estimating folder: John Fortuny - Remodel | Remodel | Latest quote: 2026-02-02`,
  },
  {
    status: `pre-engineering`,
    client_name: `Johnson Construction`,
    site_address: `TBD`,
    builder_company: `Johnson Construction`,
    notes: `Estimating folder: Johnson Construction - Garage | Garage cabinetry only | Latest quote: 2026-04-01`,
  },
  {
    status: `pre-engineering`,
    client_name: `Moss / Stone Cottage`,
    site_address: `TBD`,
    builder_company: `Moss / Stone Cottage`,
    notes: `Estimating folder: Moss - Peterson Remodel | Latest quote: 2026-04-30`,
  },
  {
    status: `pre-engineering`,
    client_name: `Newman`,
    site_address: `TBD`,
    builder_company: `Newman`,
    notes: `Estimating folder: Newman Residence | SIGNED CONTRACT ON FILE (signed ~3/6/2026) — confirm status | Latest quote: 2026-03-05`,
  },
  {
    status: `pre-engineering`,
    client_name: `Premier`,
    site_address: `TBD`,
    builder_company: `Premier`,
    notes: `Estimating folder: Premier - McClellan | No quote on file yet`,
  },
  {
    status: `pre-engineering`,
    client_name: `Premier`,
    site_address: `TBD`,
    builder_company: `Premier`,
    notes: `Estimating folder: Premier - Trupiano Residence | Long quoting history back to 2025 | Latest quote: 2026-04-29`,
  },
  {
    status: `pre-engineering`,
    client_name: `Rob Johnson Construction`,
    site_address: `395 E Jefferey Pine Ln`,
    builder_company: `Rob Johnson Construction`,
    notes: `Estimating folder: Rob Johnson Construction - 395 E Jefferey Pine Ln | Latest quote: 2026-01-26`,
  },
  {
    status: `pre-engineering`,
    client_name: `Rowley`,
    site_address: `TBD`,
    builder_company: `Rowley`,
    notes: `Estimating folder: Rowley Residence | Long quoting history; current drawings + quote 4/24/2026 — Walnut | Latest quote: 2026-04-24`,
  },
  {
    status: `pre-engineering`,
    client_name: `RSB Customs`,
    site_address: `Lot 159`,
    builder_company: `RSB Customs`,
    notes: `Estimating folder: RSB Customs - Wilcox Lot 159 | Latest quote: 2026-03-17`,
  },
  {
    status: `pre-engineering`,
    client_name: `Stancraft Construction`,
    site_address: `Hilslop`,
    builder_company: `Stancraft Construction`,
    notes: `Estimating folder: Stancraft Construction - Hilslop | Latest quote: 2026-03-26`,
  },
  {
    status: `pre-engineering`,
    client_name: `Stancraft Construction`,
    site_address: `Tri Homes Lot 3`,
    builder_company: `Stancraft Construction`,
    notes: `Estimating folder: Stancraft - Tri Homes Lot 3 Garage Add | Garage addition | Latest quote: 2026-02-25`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `1632 Union (Girardeau)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25004 | 25004 Atlas Builders - 1632 Union (Girardeau)`,
  },
  {
    status: `intake`,
    client_name: `Ginno Construction`,
    site_address: `Priest Lake cabin #3 - 74 Wedge Ct`,
    builder_company: `Ginno Construction`,
    notes: `Folder ID: 25005 | 25005 Ginno - Priest Lake cabin #3 - 74 Wedge Ct`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `3002 Lumber Lane`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25011 | 25011 Atlas Builders - 3002 Lumber Lane`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6533 W Daltrey (Ferrari)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25019 | 25019 Atlas Builders - 6533 W Daltrey (Ferrari)`,
  },
  {
    status: `intake`,
    client_name: `Stancraft Construction`,
    site_address: `Smith Lake Residence`,
    builder_company: `Stancraft Construction`,
    notes: `Folder ID: 25020 | 25020 Stancraft Construction - Smith Lake Residence`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11682 Entwistle`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25022 | 25022 Atlas Builders - 11682 Entwistle`,
  },
  {
    status: `intake`,
    client_name: `Jim & Jeannine Bohan`,
    site_address: `TBD`,
    builder_company: `Jim & Jeannine Bohan`,
    notes: `Folder ID: 25025 | 25025 Jim & Jeannine Bohan`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `Stewart Residence Cocollala`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25026 | 25026 Atlas Builders - Stewart Residence Cocollala`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `1159 Sleeping Deer`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25027 | 25027 Atlas Builders - 1159 Sleeping Deer`,
  },
  {
    status: `intake`,
    client_name: `Stancraft Construction`,
    site_address: `Tri Homes Lot 3`,
    builder_company: `Stancraft Construction`,
    notes: `Folder ID: 25029 | 25029 Stancraft - Tri Homes Lot 3`,
  },
  {
    status: `intake`,
    client_name: `Rybeck Construction`,
    site_address: `Kingston Residence`,
    builder_company: `Rybeck Construction`,
    notes: `Folder ID: 25032 | 25032 Rybeck Construction - Kingston Residence`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6575 Daltrey`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25033 | 25033 Atlas Builders - 6575 Daltrey`,
  },
  {
    status: `intake`,
    client_name: `Stancraft Construction`,
    site_address: `Copper Rock`,
    builder_company: `Stancraft Construction`,
    notes: `Folder ID: 25034 | 25034 Stancraft Construction - Copper Rock`,
  },
  {
    status: `intake`,
    client_name: `Johnson Residence`,
    site_address: `TBD`,
    builder_company: `Johnson Residence`,
    notes: `Folder ID: 25038 | 25038 Johnson Residence`,
  },
  {
    status: `intake`,
    client_name: `Pritchett Residence`,
    site_address: `TBD`,
    builder_company: `Pritchett Residence`,
    notes: `Folder ID: 25039 | 25039 Pritchett Residence`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11586 Entwistle (Reeves)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25043 | 25043 Atlas Builders - 11586 Entwistle (Reeves)`,
  },
  {
    status: `intake`,
    client_name: `Stancraft Construction`,
    site_address: `Rouse Residence`,
    builder_company: `Stancraft Construction`,
    notes: `Folder ID: 25044 | 25044 Stancraft Construction - Rouse Residence`,
  },
  {
    status: `intake`,
    client_name: `Specialty`,
    site_address: `TBD`,
    builder_company: `Specialty`,
    notes: `Folder ID: 25053 | 25053 Specialty`,
  },
  {
    status: `intake`,
    client_name: `Owens Construction`,
    site_address: `Blood Residence`,
    builder_company: `Owens Construction`,
    notes: `Folder ID: 25054 | 25054 Owens Construction - Blood Residence`,
  },
  {
    status: `intake`,
    client_name: `Garry Griswold`,
    site_address: `TBD`,
    builder_company: `Garry Griswold`,
    notes: `Folder ID: 25060 | 25060 Garry Griswold`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6602 Daltrey (Coats)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25065 | 25065 Atlas Builders - 6602 Daltrey (Coats)`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11536 Entwistle (Henrich)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25068 | 25068 Atlas Builders - 11536 Entwistle (Henrich)`,
  },
  {
    status: `intake`,
    client_name: `Brazzell Residence`,
    site_address: `TBD`,
    builder_company: `Brazzell Residence`,
    notes: `Folder ID: 25069 | 25069 Brazzell Residence`,
  },
  {
    status: `intake`,
    client_name: `Nolan Residence`,
    site_address: `TBD`,
    builder_company: `Nolan Residence`,
    notes: `Folder ID: 25071 | 25071 Nolan Residence`,
  },
  {
    status: `intake`,
    client_name: `Novell Barn`,
    site_address: `TBD`,
    builder_company: `Novell Barn`,
    notes: `Folder ID: 25072 | 25072 Novell Barn`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6538 Plant Lane`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25076 | 25076 Atlas Builders - 6538 Plant Lane`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6549 Plant Lane`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25077 | 25077 Atlas Builders - 6549 Plant Lane`,
  },
  {
    status: `intake`,
    client_name: `Stancraft Construction`,
    site_address: `Hewitt Lane, Dover`,
    builder_company: `Stancraft Construction`,
    notes: `Folder ID: 25082 | 25082 Stancraft Construction - Hewitt Lane, Dover`,
  },
  {
    status: `intake`,
    client_name: `NORTHPOINT`,
    site_address: `TBD`,
    builder_company: `NORTHPOINT`,
    notes: `Folder ID: 25083 | 25083 - NORTHPOINT`,
  },
  {
    status: `intake`,
    client_name: `Stancraft Construction`,
    site_address: `Huscroft Residence Clark Fork`,
    builder_company: `Stancraft Construction`,
    notes: `Folder ID: 25085 | 25085 Stancraft Construction - Huscroft Residence Clark Fork`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11495 Zevon (Kerns)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25089 | 25089 Atlas Builders - 11495 Zevon (Kerns)`,
  },
  {
    status: `intake`,
    client_name: `Susan Grimes 4549 E Hayden Lake Rd`,
    site_address: `TBD`,
    builder_company: `Susan Grimes 4549 E Hayden Lake Rd`,
    notes: `Folder ID: 25096 | 25096 Susan Grimes 4549 E Hayden Lake Rd`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `7336 Breaux Dr`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25100 | 25100 Cobalt Construction - 7336 Breaux Dr`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `7365 Breaux Dr`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25102 | 25102 Cobalt Construction - 7365 Breaux Dr`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `7379 Breaux Dr`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25103 | 25103 Cobalt Construction - 7379 Breaux Dr`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6509 Daltrey`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25104 | 25104 Atlas Builders - 6509 Daltrey`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `7414 Breaux Dr`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25112 | 25112 Cobalt Construction - 7414 Breaux Dr`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `7400 Breaux Dr`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25113 | 25113 Cobalt Construction - 7400 Breaux Dr`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `7388 Breaux Dr`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25114 | 25114 Cobalt Construction - 7388 Breaux Dr`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `7374 Breaux Dr`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25115 | 25115 Cobalt Construction - 7374 Breaux Dr`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2629 Lumber Ln (B)`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25118 | 25118 Cobalt Construction - 2629 Lumber Ln (B)`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11545 Zevon`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25119 | 25119 Atlas Builders - 11545 Zevon`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6581 Plant (Benefiel)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25122 | 25122 Atlas Builders - 6581 Plant (Benefiel)`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `809 E Sherman`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25123 | 25123 Atlas Builders - 809 E Sherman`,
  },
  {
    status: `intake`,
    client_name: `Stancraft Construction`,
    site_address: `Bloem Residence`,
    builder_company: `Stancraft Construction`,
    notes: `Folder ID: 25126 | 25126 Stancraft Construction - Bloem Residence`,
  },
  {
    status: `intake`,
    client_name: `David Henrie kitchen island flood damage`,
    site_address: `TBD`,
    builder_company: `David Henrie kitchen island flood damage`,
    notes: `Folder ID: 25130 | 25130 David Henrie kitchen island flood damage`,
  },
  {
    status: `intake`,
    client_name: `Sugar Mountain - Ashley`,
    site_address: `TBD`,
    builder_company: `Sugar Mountain - Ashley`,
    notes: `Folder ID: 25132 | 25132 Sugar Mountain - Ashley`,
  },
  {
    status: `intake`,
    client_name: `Conway Residence`,
    site_address: `TBD`,
    builder_company: `Conway Residence`,
    notes: `Folder ID: 25133 | 25133 Conway Residence`,
  },
  {
    status: `intake`,
    client_name: `Joyce Dallas`,
    site_address: `TBD`,
    builder_company: `Joyce Dallas`,
    notes: `Folder ID: 25146 | 25146 Joyce Dallas`,
  },
  {
    status: `intake`,
    client_name: `Jeff Glab 6549 Plant Lane`,
    site_address: `TBD`,
    builder_company: `Jeff Glab 6549 Plant Lane`,
    notes: `Folder ID: 25150 | 25150 Jeff Glab 6549 Plant Lane`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6481 Daltrey`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25151 | 25151 Atlas Builders - 6481 Daltrey`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6473 Plant`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25153 | 25153 Atlas Builders - 6473 Plant`,
  },
  {
    status: `intake`,
    client_name: `Pentz Residence`,
    site_address: `TBD`,
    builder_company: `Pentz Residence`,
    notes: `Folder ID: 25157 | 25157 - Pentz Residence`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6453 Frehley`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25160 | 25160 Atlas Builders - 6453 Frehley`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `12043 E Shadow Lane, Athol`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25161 | 25161 Atlas Builders - 12043 E Shadow Lane, Athol`,
  },
  {
    status: `intake`,
    client_name: `Krentz Residence added items`,
    site_address: `TBD`,
    builder_company: `Krentz Residence added items`,
    notes: `Folder ID: 25162 | 25162 Krentz Residence added items`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6477 Plant`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25164 | 25164 Atlas Builders - 6477 Plant`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `1215 Sleeping Deer`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25170 | 25170 Atlas Builders - 1215 Sleeping Deer`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `125 Ferry Rd, Sagle`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25171 | 25171 Atlas Builders - 125 Ferry Rd, Sagle`,
  },
  {
    status: `intake`,
    client_name: `Mills Garage`,
    site_address: `TBD`,
    builder_company: `Mills Garage`,
    notes: `Folder ID: 25173 | 25173 Mills Garage`,
  },
  {
    status: `intake`,
    client_name: `Tom and Sue Neverdahl`,
    site_address: `TBD`,
    builder_company: `Tom and Sue Neverdahl`,
    notes: `Folder ID: 25174 | 25174 Tom and Sue Neverdahl`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11410 Clapton`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25175 | 25175 Atlas Builders - 11410 Clapton`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6487 Plant`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25176 | 25176 Atlas Builders - 6487 Plant`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `Honeysuckle Commons LOT 16`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25177 | 25177 Atlas - Honeysuckle Commons LOT 16`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `Honeysuckles Commons LOT 17`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25178 | 25178 Atlas - Honeysuckles Commons LOT 17`,
  },
  {
    status: `intake`,
    client_name: `Nolan Kitchen`,
    site_address: `TBD`,
    builder_company: `Nolan Kitchen`,
    notes: `Folder ID: 25179 | 25179 Nolan Kitchen`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11556 Entwistle`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25180 | 25180 Atlas Builders - 11556 Entwistle`,
  },
  {
    status: `intake`,
    client_name: `Chaney Cabin`,
    site_address: `TBD`,
    builder_company: `Chaney Cabin`,
    notes: `Folder ID: 25183 | 25183 Chaney Cabin`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11506 Clapton (Salem plan)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25184 | 25184 Atlas Builders - 11506 Clapton (Salem plan)`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6519 Plant`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25185 | 25185 Atlas Builders - 6519 Plant`,
  },
  {
    status: `intake`,
    client_name: `Ciscel Residence`,
    site_address: `TBD`,
    builder_company: `Ciscel Residence`,
    notes: `Folder ID: 25186 | 25186 Ciscel Residence`,
  },
  {
    status: `intake`,
    client_name: `Bar 17`,
    site_address: `Greene Residence`,
    builder_company: `Bar 17`,
    notes: `Folder ID: 25190 | 25190 Bar 17 - Greene Residence`,
  },
  {
    status: `intake`,
    client_name: `Sheldon Construction`,
    site_address: `Ireland Residence`,
    builder_company: `Sheldon Construction`,
    notes: `Folder ID: 25191 | 25191 Sheldon Construction - Ireland Residence`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6553 Frehley`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25192 | 25192 Atlas Builders - 6553 Frehley`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11535 Entwistle (Salem plan)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25193 | 25193 Atlas Builders - 11535 Entwistle (Salem plan)`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11458 Clapton`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25194 | 25194 Atlas Builders - 11458 Clapton`,
  },
  {
    status: `intake`,
    client_name: `Stancraft Construction`,
    site_address: `Erm Sauna`,
    builder_company: `Stancraft Construction`,
    notes: `Folder ID: 25197 | 25197 Stancraft Construction - Erm Sauna`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11714 Entwistle`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25198 | 25198 Atlas Builders - 11714 Entwistle`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `3933 E Vulpine (Parasida Res)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25199 | 25199 Atlas Builders - 3933 E Vulpine (Parasida Res)`,
  },
  {
    status: `intake`,
    client_name: `Luther Residence`,
    site_address: `TBD`,
    builder_company: `Luther Residence`,
    notes: `Folder ID: 25203 | 25203 Luther Residence`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11532 Clapton`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25210 | 25210 Atlas Builders - 11532 Clapton`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2721 Lumber Ln (B)`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25212 | 25212 Cobalt Construction - 2721 Lumber Ln (B)`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2541 Top Saw Ln (SA)`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25215 | 25215 Cobalt Construction - 2541 Top Saw Ln (SA)`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2537 Top Saw Ln`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25216 | 25216 Cobalt Construction - 2537 Top Saw Ln`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2521 Top Saw Ln (SA)`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25217 | 25217 Cobalt Construction - 2521 Top Saw Ln (SA)`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2517 Top Saw Ln (SB)`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25218 | 25218 Cobalt Construction - 2517 Top Saw Ln (SB)`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2551 Top Saw Ln`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25219 | 25219 Cobalt Construction - 2551 Top Saw Ln`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2545 Top Saw Ln`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25220 | 25220 Cobalt Construction - 2545 Top Saw Ln`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2525 Top Saw Ln`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25221 | 25221 Cobalt Construction - 2525 Top Saw Ln`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2533 Top Saw Ln`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 25222 | 25222 Cobalt Construction - 2533 Top Saw Ln`,
  },
  {
    status: `intake`,
    client_name: `Rybeck Construction`,
    site_address: `Pinnacle`,
    builder_company: `Rybeck Construction`,
    notes: `Folder ID: 25223 | 25223 Rybeck - Pinnacle`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6379 Frehley`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25229 | 25229 Atlas Builders - 6379 Frehley`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11521 Zevon`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25231 | 25231 Atlas Builders - 11521 Zevon`,
  },
  {
    status: `intake`,
    client_name: `Stancraft Construction`,
    site_address: `Powell Residence`,
    builder_company: `Stancraft Construction`,
    notes: `Folder ID: 25235 | 25235 Stancraft Construction - Powell Residence`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11618 Entwistle`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25236 | 25236 Atlas Builders - 11618 Entwistle`,
  },
  {
    status: `intake`,
    client_name: `Castagnetto Residence`,
    site_address: `TBD`,
    builder_company: `Castagnetto Residence`,
    notes: `Folder ID: 25242 | 25242 Castagnetto Residence`,
  },
  {
    status: `intake`,
    client_name: `Premier Quality Homes`,
    site_address: `Lot 4`,
    builder_company: `Premier Quality Homes`,
    notes: `Folder ID: 25243 | 25243 Premier Quality Homes - Lot 4`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11482 Clapton`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25246 | 25246 Atlas Builders - 11482 Clapton`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `2940 Atlas Rd (Anderl Res)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25247 | 25247 Atlas Builders - 2940 Atlas Rd (Anderl Res)`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `1243 Sleeping Deer`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25248 | 25248 Atlas Builders - 1243 Sleeping Deer`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `952 Steeple Chase`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25252 | 25252 Atlas Builders - 952 Steeple Chase`,
  },
  {
    status: `intake`,
    client_name: `Kenny Debaene Jr. 7040 Rude St`,
    site_address: `TBD`,
    builder_company: `Kenny Debaene Jr. 7040 Rude St`,
    notes: `Folder ID: 25255 | 25255 Kenny Debaene Jr. 7040 Rude St`,
  },
  {
    status: `intake`,
    client_name: `Closet Magician`,
    site_address: `Ferrari`,
    builder_company: `Closet Magician`,
    notes: `Folder ID: 25256 | 25256 Closet Magician - Ferrari`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6409 Frehley`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25257 | 25257 Atlas Builders - 6409 Frehley`,
  },
  {
    status: `intake`,
    client_name: `Closet Magician`,
    site_address: `s Yoste`,
    builder_company: `Closet Magician`,
    notes: `Folder ID: 25258 | 25258 Closet Magicians Yoste`,
  },
  {
    status: `intake`,
    client_name: `Bush Legacy Builders`,
    site_address: `Red Fir Boathouse, Hope ID`,
    builder_company: `Bush Legacy Builders`,
    notes: `Folder ID: 25263 | 25263 Bush Legacy Builders - Red Fir Boathouse, Hope ID`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6364 Frehley`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25268 | 25268 Atlas Builders - 6364 Frehley`,
  },
  {
    status: `intake`,
    client_name: `Emily Moses`,
    site_address: `TBD`,
    builder_company: `Emily Moses`,
    notes: `Folder ID: 25269 | 25269 Emily Moses`,
  },
  {
    status: `intake`,
    client_name: `Bar 17`,
    site_address: `LINHOFF CABIN`,
    builder_company: `Bar 17`,
    notes: `Folder ID: 25270 | 25270 BAR 17 - LINHOFF CABIN`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `2888 W Lumber Ln`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25271 | 25271 Atlas Builders - 2888 W Lumber Ln`,
  },
  {
    status: `intake`,
    client_name: `Nick Krueger`,
    site_address: `TBD`,
    builder_company: `Nick Krueger`,
    notes: `Folder ID: 25272 | 25272 Nick Krueger`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `1934 Espinazo (Owens Res)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25273 | 25273 Atlas Builders - 1934 Espinazo (Owens Res)`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6493 Frehley`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 25275 | 25275 Atlas Builders - 6493 Frehley`,
  },
  {
    status: `intake`,
    client_name: `Uemoto 4299 Arrow Leaf Loop`,
    site_address: `TBD`,
    builder_company: `Uemoto 4299 Arrow Leaf Loop`,
    notes: `Folder ID: 25288 | 25288 Uemoto 4299 Arrow Leaf Loop`,
  },
  {
    status: `intake`,
    client_name: `RSB Customs`,
    site_address: `Drawer Fronts`,
    builder_company: `RSB Customs`,
    notes: `Folder ID: 25289 | 25289 RSB - Drawer Fronts`,
  },
  {
    status: `intake`,
    client_name: `Stancraft Construction`,
    site_address: `Bunce Kitchen Remodel`,
    builder_company: `Stancraft Construction`,
    notes: `Folder ID: 25290 | 25290 Stancraft Construction - Bunce Kitchen Remodel`,
  },
  {
    status: `intake`,
    client_name: `1159 Sleeping Deer Add On`,
    site_address: `TBD`,
    builder_company: `1159 Sleeping Deer Add On`,
    notes: `Folder ID: 25297 | 25297 - 1159 Sleeping Deer Add On`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `Office Cabs`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26002 | 26002 Atlas Office Cabs`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `2852 N Atlas (Bush)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26003 | 26003 Atlas Builders - 2852 N Atlas (Bush)`,
  },
  {
    status: `intake`,
    client_name: `Kenny Debaene - 5712 Davenport St`,
    site_address: `TBD`,
    builder_company: `Kenny Debaene - 5712 Davenport St`,
    notes: `Folder ID: 26004 | 26004 Kenny Debaene - 5712 Davenport St`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `964 Steeple Chase`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26005 | 26005 Atlas Builders - 964 Steeple Chase`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11630 Woolridge Way - Trossicks Model Home`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26007 | 26007 Atlas Builders - 11630 Woolridge Way - Trossicks Model Home`,
  },
  {
    status: `intake`,
    client_name: `DON SANDFORD`,
    site_address: `TBD`,
    builder_company: `DON SANDFORD`,
    notes: `Folder ID: 26010 | 26010 - DON SANDFORD`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `974 Steeple Chase`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26011 | 26011 Atlas Builders - 974 Steeple Chase`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11559 Entwistle`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26014 | 26014 Atlas Builders - 11559 Entwistle`,
  },
  {
    status: `intake`,
    client_name: `Castagnetto Shelves`,
    site_address: `TBD`,
    builder_company: `Castagnetto Shelves`,
    notes: `Folder ID: 26015 | 26015 Castagnetto Shelves`,
  },
  {
    status: `intake`,
    client_name: `Bissell Residence`,
    site_address: `TBD`,
    builder_company: `Bissell Residence`,
    notes: `Folder ID: 26016 | 26016 Bissell Residence`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6414 Frehley`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26020 | 26020 Atlas Builders - 6414 Frehley`,
  },
  {
    status: `intake`,
    client_name: `Spivey Residence - Premier`,
    site_address: `TBD`,
    builder_company: `Spivey Residence - Premier`,
    notes: `Folder ID: 26021 | 26021 Spivey Residence - Premier`,
  },
  {
    status: `intake`,
    client_name: `Tripp Residence`,
    site_address: `TBD`,
    builder_company: `Tripp Residence`,
    notes: `Folder ID: 26023 | 26023 Tripp Residence`,
  },
  {
    status: `intake`,
    client_name: `Sandu Codreanu Residence`,
    site_address: `TBD`,
    builder_company: `Sandu Codreanu Residence`,
    notes: `Folder ID: 26024 | 26024 Sandu Codreanu Residence`,
  },
  {
    status: `intake`,
    client_name: `GRIMES REMODEL`,
    site_address: `TBD`,
    builder_company: `GRIMES REMODEL`,
    notes: `Folder ID: 26025 | 26025 GRIMES REMODEL`,
  },
  {
    status: `intake`,
    client_name: `Mike Uemoto 3524 N Serenity Ave`,
    site_address: `TBD`,
    builder_company: `Mike Uemoto 3524 N Serenity Ave`,
    notes: `Folder ID: 26034 | 26034 Mike Uemoto 3524 N Serenity Ave`,
  },
  {
    status: `intake`,
    client_name: `Bar 17`,
    site_address: `LINHOFF DOORS`,
    builder_company: `Bar 17`,
    notes: `Folder ID: 26036 | 26036 - BAR 17 LINHOFF DOORS`,
  },
  {
    status: `intake`,
    client_name: `Bobovsky Residence`,
    site_address: `TBD`,
    builder_company: `Bobovsky Residence`,
    notes: `Folder ID: 26042 | 26042 Bobovsky Residence`,
  },
  {
    status: `intake`,
    client_name: `Chaylia & Chris Riggs`,
    site_address: `TBD`,
    builder_company: `Chaylia & Chris Riggs`,
    notes: `Folder ID: 26044 | 26044 Chaylia & Chris Riggs`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11009 E 36th Ave (Pappy's Landing Model Spokane Valley)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26049 | 26049 Atlas Builders - 11009 E 36th Ave (Pappy's Landing Model Spokane Valley)`,
  },
  {
    status: `intake`,
    client_name: `Flumerfelt Residence - Premier`,
    site_address: `TBD`,
    builder_company: `Flumerfelt Residence - Premier`,
    notes: `Folder ID: 26050 | 26050 Flumerfelt Residence - Premier`,
  },
  {
    status: `intake`,
    client_name: `RSB Customs`,
    site_address: `Osweiler`,
    builder_company: `RSB Customs`,
    notes: `Folder ID: 26054 | 26054 - RSB Customs - Osweiler`,
  },
  {
    status: `intake`,
    client_name: `White Residence`,
    site_address: `TBD`,
    builder_company: `White Residence`,
    notes: `Folder ID: 26055 | 26055 White Residence`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `3817 Vulpine (Matterhorn Parade)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26059 | 26059 Atlas Builders - 3817 Vulpine (Matterhorn Parade)`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11006 E. 36th Dr, Spokane Valley`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26064 | 26064 Atlas Builders - 11006 E. 36th Dr, Spokane Valley`,
  },
  {
    status: `intake`,
    client_name: `Maul Residence`,
    site_address: `TBD`,
    builder_company: `Maul Residence`,
    notes: `Folder ID: 26067 | 26067 - Maul Residence`,
  },
  {
    status: `intake`,
    client_name: `RSB Customs`,
    site_address: `Denoma Residence`,
    builder_company: `RSB Customs`,
    notes: `Folder ID: 26072 | 26072 - RSB Custom - Denoma Residence`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `6394 Frehley`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26077 | 26077 Atlas Builders - 6394 Frehley`,
  },
  {
    status: `intake`,
    client_name: `10573 Friar A - Kris`,
    site_address: `TBD`,
    builder_company: `10573 Friar A - Kris`,
    notes: `Folder ID: 26078 | 26078 - 10573 Friar A - Kris`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2505 Top Saw Ln`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 26079 | 26079 - Cobalt Construction - 2505 Top Saw Ln`,
  },
  {
    status: `intake`,
    client_name: `Cobalt Construction`,
    site_address: `2511 Top Saw Ln`,
    builder_company: `Cobalt Construction`,
    notes: `Folder ID: 26080 | 26080 - Cobalt Construction - 2511 Top Saw Ln`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11005 E 36th Dr, Spokane Valley`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26081 | 26081 Atlas Builders - 11005 E 36th Dr, Spokane Valley`,
  },
  {
    status: `intake`,
    client_name: `Gill Residence`,
    site_address: `TBD`,
    builder_company: `Gill Residence`,
    notes: `Folder ID: 26084 | 26084 Gill Residence`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11953 Woolridge (Olympia with upgrade)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26086 | 26086 Atlas Builders - 11953 Woolridge (Olympia with upgrade)`,
  },
  {
    status: `intake`,
    client_name: `Amanda Hughan media cabinet`,
    site_address: `TBD`,
    builder_company: `Amanda Hughan media cabinet`,
    notes: `Folder ID: 26087 | 26087 Amanda Hughan media cabinet`,
  },
  {
    status: `intake`,
    client_name: `Bar 17`,
    site_address: `WEMHOFF VANITIES`,
    builder_company: `Bar 17`,
    notes: `Folder ID: 26091 | 26091 - BAR 17 - WEMHOFF VANITIES`,
  },
  {
    status: `intake`,
    client_name: `BISSELL TRIM PACKAGE`,
    site_address: `TBD`,
    builder_company: `BISSELL TRIM PACKAGE`,
    notes: `Folder ID: 26093 | 26093 - BISSELL TRIM PACKAGE`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11692 Woolridge (Victoria with upgrade)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26095 | 26095 Atlas Builders - 11692 Woolridge (Victoria with upgrade)`,
  },
  {
    status: `intake`,
    client_name: `Stancraft Construction`,
    site_address: `Copper Rock Gazebo ADU`,
    builder_company: `Stancraft Construction`,
    notes: `Folder ID: 26096 | 26096 Stancraft Construction - Copper Rock Gazebo ADU`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `11530 Woolridge (Olympia with upgrade)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26098 | 26098 Atlas Builders - 11530 Woolridge (Olympia with upgrade)`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `5895 Moresby (Olympia with upgrade)`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26099 | 26099 Atlas Builders - 5895 Moresby (Olympia with upgrade)`,
  },
  {
    status: `intake`,
    client_name: `Atlas Builders`,
    site_address: `5871 Moresby`,
    builder_company: `Atlas Builders`,
    notes: `Folder ID: 26109 | 26109 Atlas Builders - 5871 Moresby`,
  },
  {
    status: `intake`,
    client_name: `Jeremy Riggs`,
    site_address: `TBD`,
    builder_company: `Jeremy Riggs`,
    notes: `Folder ID: 26110 | 26110 Jeremy Riggs`,
  },
  {
    status: `intake`,
    client_name: `Jathan Project`,
    site_address: `TBD`,
    builder_company: `Jathan Project`,
    notes: `Folder ID: 26115 | 26115 - Jathan Project`,
  },
] as const;

async function main() {
  const now = new Date().toISOString();
  let inserted = 0, skipped = 0;
  for (const j of jobs) {
    const { id, seq } = await nextJobId();
    try {
      await sql`
        INSERT INTO jobs (id, seq, created_at, status, job_type,
                          client_name, site_address, builder_company,
                          notes, mod_residential)
        VALUES (${id}, ${seq}, ${now}, ${j.status}, 'residential',
                ${j.client_name}, ${j.site_address}, ${j.builder_company},
                ${j.notes}, 1)
        ON CONFLICT (id) DO NOTHING
      `;
      console.log(`✓ ${id}  ${j.client_name}`);
      inserted++;
    } catch (e) {
      console.error(`✗ ${id}`, e);
      skipped++;
    }
  }
  console.log(`\nDone — inserted: ${inserted}, errors: ${skipped}`);
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });